### ISSUE TITLE
Is it possible to release the FreeCAD libpack build without the `-1` prepended to the filename?

### ISSUE THREAD

**Issue by luzpaz** [donovaly/FreeCADInstProj#4]
![Screenshot_20220614_073327](https://user-images.githubusercontent.com/4140247/173568023-22c45986-0582-4ade-b66c-727a75573032.png)

**Comment by donovaly** [comment]
The "-1" is the installer version number. it is independent of the FreeCAD release. For example when users report now an issue with the installer, I can fix them and this installer will get the suffix "-2". (You see in the beta1 release I needed even 5 versions until it was stable.)

Now I already got reports of wrong weblinks in the installer so probably there will be a "-2" installer the next days.

**Comment by luzpaz** [comment]
Ok. Thanks
